export const PLEASE_TRY_AGAIN_AFTER_5_MINUES =
  'PLEASE_TRY_AGAIN_AFTER_5_MINUES';
export const PLEASE_TRY_AGAIN_A_FEW_MINUTES = 'PLEASE_TRY_AGAIN_A_FEW_MINUTES';
export const EXCEED_TIMES_WRONG_OTP = 'EXCEED_TIMES_WRONG_OTP';
export const OTP_NOT_VALID = 'OTP_NOT_VALID';
export const THIS_PHONE_NUMBER_IS_EXISTED = 'THIS_PHONE_NUMBER_IS_EXISTED';
export const USER_WAS_BLOCKED = 'USER_WAS_BLOCKED';
export const OTP_CANNOT_BE_CREATED_MORE_THAN_ONCE_IN_5_MINUTES =
  'OTP_CANNOT_BE_CREATED_MORE_THAN_ONCE_IN_5_MINUTES';
