import { FC, useEffect } from 'react';
import style from './Layout.module.scss';

import Head from 'next/head';
import { useRouter } from 'next/router';
import { getProfile } from '@/redux/slice/userSlice';
import { useAppSelector, useAppDispatch, RootState } from '@/redux';

import { Footer } from '../common';
import Header from '../common/Header/Header';
import Loading from '../Loading/Loading';
import Welcome from '@/containers/Welcome/Welcome';

export const Layout: FC<ILayout> = ({
  header,
  children,
  footer = <Footer />,
  isHeader = true,
  isFooter = true,
  title,
  islogo,
}) => {
  const router = useRouter();
  const location = router.pathname;
  const dispatch = useAppDispatch();
  const isLogin = useAppSelector((state: RootState) => state.userSlice.isLogin);
  useEffect(() => {
    dispatch(getProfile());
  }, [dispatch, location]);

  if (!isLogin && location !== '/auth/login' && location !== '/') {
    router.push('/');
    return <Loading />;
  }

  if (isLogin && location === '/auth/login') {
    router.push('/chat');
    return <Loading />;
  }

  return (
    <div className={style.layout}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isHeader ? <Header isLogo={islogo} /> : ''}
      <div className={style.children}>{children}</div>
      {isFooter && footer}
    </div>
  );
};
