import { FC, useEffect, useState } from 'react';
import style from './Layout.module.scss';

import Head from 'next/head';
import { useRouter } from 'next/router';
import { useAppSelector, RootState, useAppDispatch } from '@/redux';
import { Footer, Header } from '../common';
import Loading from '../Loading/Loading';
import { getProfile } from '@/redux/slice/userSlice';
import { ILayout } from '@/@type/components';

export const Layout: FC<ILayout> = ({
  children,
  isHeader = true,
  isFooter = true,
  isLogo = false,
  title,
}) => {
  const router = useRouter();
  const location = router.pathname;
  const dispatch = useAppDispatch();
  const [isFetch, setIsFectch] = useState(false);
  const myState = useAppSelector((state: RootState) => state.userSlice);

  const fecthInfo = async () => {
    const check = (await dispatch(getProfile())).payload;

    if (check) {
      setIsFectch(true);
    }
  };

  useEffect(() => {
    // fecthInfo();
  }, []);

  if (
    !myState.isLogin &&
    location !== '/auth/login' &&
    location !== '/' &&
    location !== '/auth/loginsocial' &&
    location !== 'auth/loginsocial#_='
  ) {
    router.push('/');
  }
  if (location === '/auth/login' && myState.step === 0) {
    router.push('/');
  }
  if (
    myState.isLogin &&
    (location === '/auth/login' ||
      location === '/auth/loginsocial' ||
      location === 'auth/loginsocial#_=')
  ) {
    router.push('/finding');
  }

  return (
    <div className={style.layout}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isHeader && <Header isLogo={isLogo} />}
      <div className={style.children}>{children}</div>
      {isFooter && <Footer />}
    </div>
  );
};
